### PR TITLE
fix: dual selected tab issue to be mutually exclusive

### LINKED ISSUE #116: bug: stats-in-detail page - 2 tabs selected
Make sure selection is mutually exclusive:

Screenshot 2024-07-28 at 12 32 39 PM

### PR DESCRIPTION
**Pull request by shlomomdahan**
Screenshot 2024-07-28 at 12 34 56 PM

closes #116

### CODE REVIEW

**Review by Vandit1604 — APPROVED** [review]
Looks good to me.
Thanks @shlomomdahan

**Review by krisstern — DISMISSED** [review]

File: src/hooks/useSelectionState.ts [hunk 1]
```diff
@@ -8,13 +8,13 @@ const useSelectionState = () => {
     const handleChartSelect = (chart: string) => {
         setSelectedChart(chart)
         setSelectedTab('overall')
-        setSelectedYear(null)
+        setSelectedYear('null')
     }
 
     const handleYearSelect = (year: string | null) => {
```
Comment (krisstern) [inline src/hooks/useSelectionState.ts:14]:
```suggestion
    const handleYearSelect = (year: string) => {
```

**Review by krisstern — APPROVED** [review]
LGTM
